// Shared across app/api/setup (initial auto-generation), the add/accept
// enforcement endpoints, and the dashboard's usage display — one source of
// truth so these numbers can't drift out of sync with each other again.
export const PLAN_PROMPT_LIMITS: Record<string, number> = { starter: 10, growth: 20, enterprise: 50 };
export const FREE_PROMPT_LIMIT = 10;

export function promptLimitForPlan(plan: string | null | undefined): number {
  return plan ? PLAN_PROMPT_LIMITS[plan] ?? FREE_PROMPT_LIMIT : FREE_PROMPT_LIMIT;
}

// How many of a brand's tracked prompts /api/setup AI-generates on the user's
// behalf — the remainder of PLAN_PROMPT_LIMITS is left for the user to fill in
// themselves during onboarding (the wizard in app/setup/page.tsx gates its
// "add your own" box on PLAN_PROMPT_LIMITS minus however many are currently
// selected, so deselecting an AI-generated prompt always frees up a slot).
export const PLAN_AUTO_GENERATED_PROMPTS: Record<string, number> = { starter: 10, growth: 15, enterprise: 40 };

export function autoGeneratedPromptsForPlan(plan: string | null | undefined): number {
  return plan ? PLAN_AUTO_GENERATED_PROMPTS[plan] ?? FREE_PROMPT_LIMIT : FREE_PROMPT_LIMIT;
}

// How many brands a plan can track — enforced in app/api/setup (blocks adding
// a new brand past the limit) and mirrored in the dashboard's "at limit" UI
// gate. Single source of truth so the two can't disagree on the number again.
export const BRAND_LIMITS: Record<string, number> = { starter: 1, growth: 2, enterprise: 3 };
export const FREE_BRAND_LIMIT = 1;

export function brandLimitForPlan(plan: string | null | undefined): number {
  return plan ? BRAND_LIMITS[plan] ?? FREE_BRAND_LIMIT : FREE_BRAND_LIMIT;
}

// Included monthly Web+LLM Analytics events per plan (web_visits + bot_visits
// combined). Usage past this is metered via Dodo credits — see
// lib/analytics-billing.ts and inngest/functions/analytics-billing.ts.
export const PLAN_ANALYTICS_EVENT_QUOTAS: Record<string, number> = { starter: 20000, growth: 100000, enterprise: 500000 };

export function analyticsEventQuotaForPlan(plan: string | null | undefined): number {
  return plan ? PLAN_ANALYTICS_EVENT_QUOTAS[plan] ?? 0 : 0;
}

// Grace period after a renewal payment fails (Dodo's `subscription.on_hold`
// webhook — see app/api/dodo/webhook/route.ts) before we lock the account
// out, on top of whatever retries Dodo's own dunning process runs.
export const PAYMENT_GRACE_PERIOD_MS = 3 * 24 * 60 * 60 * 1000;

type UserPlanRow = {
  dodo_customer_id: string | null;
  dodo_subscription_id: string | null;
  payment_failed_at?: string | null;
};

// True once a subscriber should be fully locked out of the product — no
// brand data visible, no scans running — until they reactivate. Two paths:
// Dodo has fully cancelled/expired the subscription (dodo_subscription_id
// cleared), or a renewal payment has been failing longer than our grace
// period. Does not delete any data — reactivating restores access instantly.
export function isLapsedSubscriber(row: UserPlanRow | null | undefined): boolean {
  if (!row) return false;
  if (row.dodo_customer_id && !row.dodo_subscription_id) return true;
  if (row.payment_failed_at) {
    return Date.now() - new Date(row.payment_failed_at).getTime() > PAYMENT_GRACE_PERIOD_MS;
  }
  return false;
}

// True for any account that isn't a currently-paying subscriber — never
// subscribed at all, or lapsed (cancelled/expired/payment-grace-exceeded).
// Shared sync predicate behind requiresPaywall (per-request DB check) and
// the scheduled-scan cron (bulk-filters an already-fetched plan list) so
// the two can't drift out of sync on what counts as "not paying".
export function isUnpaidPlan(row: UserPlanRow | null | undefined): boolean {
  return !row?.dodo_subscription_id || isLapsedSubscriber(row);
}

// True when the requester's real, sensitive data should be redacted server-
// side (never subscribed, OR cancelled/expired/payment-grace-exceeded).
// requireBrandAccess only verifies *ownership* — this is the plan check that
// was missing from every data-serving route, which is what actually made
// the dashboard's blur/decoy UI real security instead of decoration: without
// this, a free-tier user's own valid session could pull the same data
// straight from the API, no client rendering involved.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function requiresPaywall(db: any, ownerId: string): Promise<boolean> {
  const { data: row } = await db
    .from("user_plans")
    .select("dodo_customer_id, dodo_subscription_id, payment_failed_at")
    .eq("user_id", ownerId)
    .maybeSingle();
  return isUnpaidPlan(row);
}

// Days left in the failed-payment grace period, for a dashboard warning
// banner — null when there's nothing to warn about (no failure, or already
// past grace, in which case isLapsedSubscriber is the relevant check).
export function gracePeriodDaysLeft(row: UserPlanRow | null | undefined): number | null {
  if (!row?.payment_failed_at) return null;
  if (row.dodo_customer_id && !row.dodo_subscription_id) return null;
  const remainingMs = PAYMENT_GRACE_PERIOD_MS - (Date.now() - new Date(row.payment_failed_at).getTime());
  if (remainingMs <= 0) return null;
  return Math.ceil(remainingMs / (24 * 60 * 60 * 1000));
}

// Costs scale with how many prompts actually get scanned — paused ones are
// skipped by every scan (see isDueForScheduledScan), so only active prompts
// count against the limit. Existing brands already over their limit are
// grandfathered: this only ever blocks *adding* more, never removes anything.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function assertUnderPromptLimit(db: any, userId: string, brandId: string): Promise<{ ok: true } | { ok: false; limit: number }> {
  const { data: planRow } = await db.from("user_plans").select("plan, dodo_subscription_id").eq("user_id", userId).maybeSingle();
  const plan = planRow?.dodo_subscription_id ? planRow.plan : null;
  const limit = promptLimitForPlan(plan);

  const { count } = await db
    .from("tracked_prompts")
    .select("id", { count: "exact", head: true })
    .eq("brand_id", brandId)
    .neq("status", "paused");

  if ((count ?? 0) >= limit) return { ok: false, limit };
  return { ok: true };
}
